#!/bin/sh                                                                     

set -e
mode=$1
source_package=teddix-agent

case "$mode" in
  configure )
    prev_version=$2

    cp -v /usr/share/teddix-agent/init.d/teddix-agent.debian /etc/init.d/teddix-agent 
    openssl req -new -x509 -keyout /etc/teddix/agent.key -out /etc/teddix/agent.crt -days 365 -nodes -config /etc/ssl/openssl.cnf -batch
    [ ! -d /etc/teddix ] && mkdir /etc/teddix
    [ ! -f /etc/teddix/teddix.conf ] && cp -v /usr/share/teddix/teddix.conf /etc/teddix/teddix.conf
    /etc/init.d/teddix-agent start
    update-rc.d teddix-agent defaults

    ;;
esac

#DEBHELPER#

