#!/bin/sh                                                                     

set -e
mode=$1
source_package=teddix-web

case "$mode" in
  configure )
    prev_version=$2

    chmod 777 /usr/share/teddix-web/teddixweb/static/charts

    [ -d /etc/teddix ] || mkdir /etc/teddix
    [ -f /etc/teddix/websettings.py ] || cp -v /usr/share/teddix/websettings.py /etc/teddix
    chmod 600 /etc/teddix/websettings.py

    ;;
esac

#DEBHELPER#

