Document: teddix
Title: Debian teddix Manual
Author: <insert document author here>
Abstract: This manual describes what teddix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/teddix/teddix.sgml.gz

Format: postscript
Files: /usr/share/doc/teddix/teddix.ps.gz

Format: text
Files: /usr/share/doc/teddix/teddix.text.gz

Format: HTML
Index: /usr/share/doc/teddix/html/index.html
Files: /usr/share/doc/teddix/html/*.html
